db_driver: "postgres"
db_credentials: "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable"
server_addr: "0.0.0.0:8080" # to run in docker, need 0.0.0.0 instead of localhost.
token_symmetric_key: "12345678901234567890123456789012"
access_token_duration: 15m
